default_config:

logger:
  default: info
  logs:
    custom_components.pool_esp: debug          
    custom_components.pool_esp.test_runner: debug          
    custom_components.pool_esp.estimator: debug          
    custom_components.pool_esp.state_machine: debug          
    custom_components.pool_esp.persistence: debug  
homeassistant:
  time_zone: America/New_York

